repos:
  - repo: local
    hooks:
      - id: pre-commit-sequence
        name: Pre Commit Sequence (Tests, Type Checks, Env Dependency Update)
        entry: bash -c
        language: system
        types: [python]
        args:
          - >
            source ~/miniconda3/etc/profile.d/conda.sh &&
            conda activate MacroSim &&
            pytest tests &&
            mypy macrosim/ &&
            conda env export -n MacroSim | grep -v "^prefix: " > ./dev/conda_env.yaml &&
            git diff --quiet ./dev/conda_env.yaml || git add ./dev/conda_env.yaml