site_name: MacroSim
site_author: Ege Güney Kıymaç

nav:
  - Home: index.md
  - Class Documentations:
    - SeriesAccessor: class_docs/SeriesAccessor.md
    - EqSearch: class_docs/EqSearch.md
    - GrowthPatternDetector: class_docs/GrowthPatternDetector.md
    - BaseVarSelector: class_docs/BaseVarSelector.md
    - BaseVarModel: class_docs/BaseVarModel.md
    - SimEngine: class_docs/SimEngine.md
  - About:
    - License: LICENSE

theme:
  name: mkdocs
  color_mode: auto
  user_color_mode_toggle: true

markdown_extensions:
  - pymdownx.arithmatex:
      generic: true

extra_javascript:
  - ./javascripts/katex.js
  - https://unpkg.com/katex@0/dist/katex.min.js
  - https://unpkg.com/katex@0/dist/contrib/auto-render.min.js

extra_css:
  - https://unpkg.com/katex@0/dist/katex.min.css