site_name: MacroSim Docs
site_author: Ege Güney Kıymaç

nav:
  - Home: index.md

  - Class Documentations:
    - SeriesAccessor: class_docs/SeriesAccessor.md
    - EqSearch: class_docs/EqSearch.md
    - GrowthPatternDetector: class_docs/GrowthPatternDetector.md
    - SimEngine: class_docs/SimEngine.md

  - About:
    - License: LICENSE

markdown_extensions:
  - pymdownx.arithmatex:
      generic: true
extra_javascript:
  - https://cdnjs.cloudflare.com/ajax/libs/KaTeX/0.16.4/katex.min.js
  - https://cdnjs.cloudflare.com/ajax/libs/KaTeX/0.16.4/contrib/auto-render.min.js
extra_css:
  - https://cdnjs.cloudflare.com/ajax/libs/KaTeX/0.16.4/katex.min.css