import pandas as pd
from .StatsTypes import DATA as DATA, FREQ_TO_PERIODS_PER_YEAR as FREQ_TO_PERIODS_PER_YEAR, LAG as LAG, PVAL as PVAL, SeriesInfo as SeriesInfo, TestStats as TestStats
from dataclasses import dataclass
from typing import Literal

class Causality:
    def __init__(self) -> None: ...
    @staticmethod
    def get_freq(df: DATA) -> int: ...
    @staticmethod
    def get_batch_size(data: DATA) -> int: ...
    @staticmethod
    def max_lag(data: DATA) -> int: ...
    @staticmethod
    def perm_gct(df: pd.DataFrame, stat: Literal['F', 'chi2', 'lr'] = 'F', alpha: float = 0.05) -> dict[str, dict[str, list[tuple[LAG, PVAL]]]]: ...
    @staticmethod
    def rolling_perm_gct(df: DATA, stat: Literal['F', 'chi2', 'lr'] = 'F', alpha: float = 0.05, batch_size: int | None = None) -> dict[str, dict[str, list[tuple[LAG, PVAL]]]]: ...
    @staticmethod
    def common_lag(gct_res: dict[str, dict[str, list[tuple[LAG, PVAL]]]]) -> LAG: ...

@dataclass
class CausalityResult:
    df: DATA
    rolling = ...
    tests = ...
    is_causal = ...
    common_lag = ...
    def __post_init__(self) -> None: ...

class CausalityAccessor:
    def __init__(self, pandas_obj: DATA) -> None: ...
    @property
    def results(self) -> CausalityResult: ...
    @property
    def tests(self) -> dict[str, dict[str, list[tuple[LAG, PVAL]]]]: ...
    @property
    def rolling(self) -> dict[str, dict[str, list[tuple[LAG, PVAL]]]]: ...
    @property
    def is_causal(self) -> dict[str, Literal[SeriesInfo.CAUSAL, SeriesInfo.NON_CAUSAL]]: ...
    @property
    def common_lag(self) -> LAG: ...
