from .StatsTypes import DATA as DATA, LAG as LAG, PVAL as PVAL, SeriesInfo as SeriesInfo
from dataclasses import dataclass
from typing import Literal

class Stationarity:
    def __init__(self) -> None: ...
    @staticmethod
    def max_lag(df: DATA) -> LAG: ...
    @staticmethod
    def adf(series: DATA) -> tuple[str, dict[LAG, PVAL]]: ...
    @staticmethod
    def frame_adf(df: DATA) -> dict[str, dict[LAG, PVAL]]: ...
    @staticmethod
    def common_lag(adf_result: dict[str, dict[int, PVAL]]) -> LAG: ...

@dataclass
class StationarityResult:
    df: DATA
    tests = ...
    is_stationary = ...
    common_lag = ...
    def __post_init__(self) -> None: ...

class StationarityAccessor:
    def __init__(self, pandas_obj: DATA) -> None: ...
    @property
    def results(self): ...
    @property
    def tests(self) -> dict[str, dict[LAG, PVAL]]: ...
    @property
    def is_stationary(self) -> dict[str, Literal[SeriesInfo.STATIONARY, SeriesInfo.NON_STATIONARY]]: ...
    @property
    def common_lag(self) -> LAG: ...
