import pandas as pd
import sympy as sp
from AutoReg import EXTRA_GLOBALS as EXTRA_GLOBALS
from pysr import PySRRegressor, TemplateExpressionSpec
from typing import Callable

MODEL_LOCALS: dict[str, Callable]

def get_expr(X: pd.DataFrame, target: str) -> TemplateExpressionSpec: ...
def model_config(X: pd.DataFrame, target: str, spec: TemplateExpressionSpec | None = None, log: bool = True, logdir_child: str | None = None) -> PySRRegressor: ...
def subs_expr(model: PySRRegressor) -> tuple[list, sp.Expr]: ...
def fit(X: pd.DataFrame, y: pd.Series | pd.DataFrame, template_spec: bool = True) -> PySRRegressor: ...
