import abc
import pandas as pd
from abc import ABC, abstractmethod
from macrosim.stats.StatsTypes import DATA as DATA, FREQ_TO_PERIODS_PER_YEAR as FREQ_TO_PERIODS_PER_YEAR, LAG as LAG
from pysr import PySRRegressor, TemplateExpressionSpec
from typing import Callable, Literal

def run_batch_process(args): ...
def ssqrt(x: float) -> float: ...

EXTRA_GLOBALS: dict[str, Callable[[float], float]]

class _AbstractPredictor(ABC, metaclass=abc.ABCMeta):
    @property
    @abstractmethod
    def target(self) -> str: ...
    @property
    @abstractmethod
    def target_lags(self) -> LAG: ...
    @property
    @abstractmethod
    def causal_lag_positions(self) -> dict[str, LAG]: ...
    @property
    @abstractmethod
    def ordered_features(self) -> dict[int, list[str]] | list[str]: ...
    @property
    @abstractmethod
    def fit_eval(self) -> dict[str, float | int]: ...
    @abstractmethod
    def predict(self, X: pd.DataFrame, t_range: pd.DatetimeIndex) -> pd.Series: ...
    def reconstruct_lags(self, X: pd.DataFrame, t_range: pd.DatetimeIndex) -> pd.DataFrame: ...

class _Predictor(_AbstractPredictor):
    def __init__(self, model: PySRRegressor, target: str, target_lags: LAG, causal_lag_positions: dict[str, LAG], fit_eval: dict[str, float | int] | None = None) -> None: ...
    def predict(self, X: pd.DataFrame, t_range: pd.DatetimeIndex) -> pd.Series: ...
    @property
    def target(self) -> str: ...
    @property
    def target_lags(self) -> LAG: ...
    @property
    def causal_lag_positions(self) -> dict[str, LAG]: ...
    @property
    def ordered_features(self) -> list[str]: ...
    @property
    def model(self) -> PySRRegressor: ...
    @property
    def fit_eval(self) -> dict[str, float | int]: ...

class _BatchedPredictor(_AbstractPredictor):
    def __init__(self, eqs: dict[int, Callable], ordered_features: dict[int, list[str]], target: str, target_lags: LAG, causal_lag_positions: dict[str, LAG], fit_eval: dict[str, float | int] | None = None) -> None: ...
    def predict(self, X: pd.DataFrame, t_range: pd.DatetimeIndex) -> pd.Series: ...
    @property
    def target(self) -> str: ...
    @property
    def target_lags(self) -> LAG: ...
    @property
    def causal_lag_positions(self) -> dict[str, LAG]: ...
    @property
    def ordered_features(self) -> dict[int, list[str]]: ...
    @property
    def eqs(self) -> dict[int, Callable]: ...
    @property
    def fit_eval(self) -> dict[str, float | int]: ...
    def __getitem__(self, key: int) -> Callable: ...
    def __len__(self) -> int: ...

class AutoReg:
    df: pd.DataFrame
    target: str
    freq: int
    n_lags: LAG
    causal_lag_positions: dict[str, LAG]
    model: PySRRegressor
    batched_model: _BatchedPredictor
    def __init__(self, df: pd.DataFrame, target: str) -> None: ...
    @staticmethod
    def get_freq(df: DATA) -> int: ...
    def get_target_lags(self) -> pd.DataFrame: ...
    def get_causal_lags(self) -> pd.DataFrame | None: ...
    def process_data(self) -> tuple[pd.DataFrame, pd.Series]: ...
    def shuffle_batch(self, n: int) -> tuple[enumerate, tuple[pd.DataFrame, pd.Series]]: ...
    def get_expr(self) -> TemplateExpressionSpec: ...
    def model_config(self, spec: TemplateExpressionSpec | None = None, log: bool = True, logdir_child: str | None = None) -> PySRRegressor: ...
    def fit(self, template_spec: bool = True) -> tuple[_Predictor, dict[str, float | int]]: ...
    def batch_fit(self, n: int, *, template_spec: bool = True, parallel: bool = True) -> _BatchedPredictor: ...
    def predict(self, data: pd.DataFrame, t_range: pd.DatetimeIndex, model_type: Literal['ensemble', 'single'] | None) -> pd.Series: ...
